[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "narwhals"
version = "0.9.21"
authors = [
  { name="Marco Gorelli", email="33491632+MarcoGorelli@users.noreply.github.com" },
]
description = "Extremely lightweight compatibility layer between pandas, Polars, cuDF, and Modin"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.optional-dependencies]
pandas = ["pandas>=1.1.5"]
polars = ["polars>=0.20.3"]
pyarrow = ['pyarrow>=11.0.0']

[project.urls]
"Homepage" = "https://github.com/narwhals-dev/narwhals"
"Bug Tracker" = "https://github.com/narwhals-dev/narwhals"

[tool.ruff]
line-length = 90
fix = true
target-version = "py38"

lint.select = [
  "ALL",
]
lint.ignore = [
  'ANN101', # deprecated and will be removed in future ruff release: https://docs.astral.sh/ruff/rules/missing-type-self/
  'ANN401',
  'C901',
  'COM812',
  'D',
  'DTZ001',
  'E501',
  'FIX002',
  'ISC001',  # Keep to avoid conflic with ruff-format
  'PD901',  # This is a auxiliary library so dataframe variables have no concrete business meaning
  'PLR0912',
  'PLR2004',
  'RET505', # Keep, this will become easier to fix after #363 is merged
  'S101',
  'SLF001',
  'TD002',
  'TD003',
]

[tool.ruff.lint.isort]
force-single-line = true

[tool.ruff.format]
docstring-code-format = true

[tool.pytest.ini_options]
filterwarnings = [
  "error",
  'ignore:distutils Version classes are deprecated:DeprecationWarning',
]
xfail_strict = true
markers = ["slow: marks tests as slow (deselect with '-m \"not slow\"')"]

[tool.coverage.run]
plugins = ["covdefaults"]

[tool.coverage.report]
exclude_also = [
  "> POLARS_VERSION",
  "if sys.version_info() <",
  "if implementation == \"modin\"",
  "if implementation == \"cudf\"",
]

[tool.mypy]
strict = true

[[tool.mypy.overrides]]
# the pandas API is just too inconsistent for type hinting to be useful.
module = [
    "pandas.*",
    "cudf.*",
    "modin.*",
]
ignore_missing_imports = true
