[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "narwhals"
version = "0.9.17"
authors = [
  { name="Marco Gorelli", email="33491632+MarcoGorelli@users.noreply.github.com" },
]
description = "Extremely lightweight compatibility layer between pandas, Polars, cuDF, and Modin"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.optional-dependencies]
pandas = ["pandas>=1.1.5"]
polars = ["polars>=0.20.3"]
pyarrow = ['pyarrow>=11.0.0']

[project.urls]
"Homepage" = "https://github.com/narwhals-dev/narwhals"
"Bug Tracker" = "https://github.com/narwhals-dev/narwhals"

[tool.ruff]
line-length = 90
fix = true
target-version = "py38"

lint.select = [
  "ALL",
]
lint.ignore = [
  'A001',
  'A003',
  'ANN101',
  'ANN401',
  'ARG002',  # todo: enable
  'ARG003',  # todo: enable
  'C901',
  'COM812',
  'D',
  'DTZ',
  'E501',
  'EM101',  # todo: enable
  'ERA001',  # todo: enable
  'FBT003',  # todo: enable
  'FIX',
  'ICN001',
  'ISC001',
  'PD',
  'PLR0911',
  'PLR0912',
  'PLR5501',
  'PLR2004',
  'PT011',
  'PTH',
  'RET505',
  'S',
  'SLF001',
  'TD',
  'TRY003',  # todo: enable
  'TRY004'
]

[tool.ruff.lint.isort]
force-single-line = true

[tool.ruff.format]
docstring-code-format = true

[tool.pytest.ini_options]
filterwarnings = [
  "error",
  'ignore:distutils Version classes are deprecated:DeprecationWarning',
]
xfail_strict = true
markers = ["slow: marks tests as slow (deselect with '-m \"not slow\"')"]

[tool.coverage.run]
plugins = ["covdefaults"]

[tool.coverage.report]
exclude_also = [
  "> POLARS_VERSION",
  "if sys.version_info() <",
  "if implementation == \"modin\"",
  "if implementation == \"cudf\"",
]

[tool.mypy]
strict = true

[[tool.mypy.overrides]]
# the pandas API is just too inconsistent for type hinting to be useful.
module = [
    "pandas.*",
    "cudf.*",
    "modin.*",
]
ignore_missing_imports = true


[tool.pylint.main]
fail-on = ["I"]
fail-under = 10
ignore = ["third_party"]
ignore-patterns = []
jobs = 8
load-plugins = [
    "pylint.extensions.bad_builtin",
    "pylint.extensions.broad_try_clause",
    "pylint.extensions.code_style",
    "pylint.extensions.check_elif",
    "pylint.extensions.code_style",
    "pylint.extensions.comparison_placement",
    "pylint.extensions.confusing_elif",
    "pylint.extensions.consider_ternary_expression",
    "pylint.extensions.consider_refactoring_into_while_condition",
    "pylint.extensions.dict_init_mutate",
    "pylint.extensions.docparams",
    "pylint.extensions.docstyle",
    "pylint.extensions.dunder",
    "pylint.extensions.empty_comment",
    "pylint.extensions.eq_without_hash",
    "pylint.extensions.for_any_all",
    "pylint.extensions.magic_value",
    "pylint.extensions.mccabe",
    "pylint.extensions.no_self_use",
    "pylint.extensions.overlapping_exceptions",
    "pylint.extensions.private_import",
    "pylint.extensions.redefined_loop_name",
    "pylint.extensions.redefined_variable_type",
    "pylint.extensions.set_membership",
    "pylint.extensions.typing",
    "pylint.extensions.while_used",
]
py-version = "3.8"


[tool.pylint."messages control"]
disable = [
    "missing-function-docstring",
    "missing-module-docstring",
    "missing-class-docstring",
    "protected-access",                        # TODO: Enable
    "line-too-long",                           # TODO: Enable
    "too-many-arguments",                      # TODO: Enable
    "import-outside-toplevel",                 # TODO: Enable
    "redefined-builtin",                       # TODO: Enable
    "redefined-outer-name",                    # TODO: Enable
    "too-few-public-methods",                  # TODO: Enable
    "too-many-public-methods",                 # TODO: Enable
    "too-many-locals",                         # TODO: Enable
    "too-many-branches",                       # TODO: Enable
    "too-many-return-statements",              # TODO: Enable
    "no-member",                               # TODO: Enable
    "fixme",                                   # TODO: Enable
    "consider-using-dict-items",               # TODO: Enable
    "no-else-return",                          # TODO: Enable
    "unsubscriptable-object",                  # TODO: Enable
    "invalid-name",                            # TODO: Enable
    "wrong-import-order",                      # TODO: Enable
    "unnecessary-dunder-call",                 # TODO: Enable
    "unspecified-encoding",                    # TODO: Enable
    "subprocess-run-check",                    # TODO: Enable
    "too-many-boolean-expressions",            # TODO: Enable
    "import-self",                             # TODO: Enable
    "unused-argument",                         # TODO: Enable
    "possibly-used-before-assignment",         # TODO: Enable
    "too-many-lines",                          # TODO: Enable
    "unused-variable",                         # TODO: Enable
    "comparison-with-itself",                  # TODO: Enable
    "useless-parent-delegation",               # TODO: Enable
    "ungrouped-imports",                       # TODO: Enable
    "reimported",                              # TODO: Enable
    "cyclic-import",                           # TODO: Enable
    "duplicate-code",                          # TODO: Enable
    "magic-value-comparison",                  # TODO: Enable
    "no-self-use",                             # TODO: Enable
    "consider-using-namedtuple-or-dataclass",  # TODO: Enable
    "redefined-variable-type",                 # TODO: Enable
    "use-set-for-membership",                  # TODO: Enable
    "eq-without-hash",                         # TODO: Enable
    "too-complex",                             # TODO: Enable
    "consider-using-tuple",                    # TODO: Enable
    "consider-using-assignment-expr",          # TODO: Enable
    "docstring-first-line-empty",              # TODO: Enable
    "too-many-try-statements",                 # TODO: Enable
    "import-error",                            # TODO: Enable
    "wrong-import-position",                   # TODO: Enable
    "expression-not-assigned",                 # TODO: Enable
    "implicit-str-concat",                     # TODO: Enable
    "redefined-loop-name",                     # TODO: Enable
    "import-private-name",                     # TODO: Enable
]

enable = [
    "bad-inline-option",
    "file-ignored",
    "useless-suppression",
    "deprecated-pragma",
    "use-symbolic-message-instead",
    "deprecated-pragma",
    "file-ignored",
]

[tool.pylint.similarities]
ignore-comments = true
ignore-docstrings = true
ignore-signatures = true
min-similarity-lines = 4


[tool.pylint.design]
max-args = 7
max-attributes = 7
max-bool-expr = 5
max-branches = 12
max-complexity = 10
max-locals = 15
max-parents = 7
max-public-methods = 20
max-returns = 6
max-statements = 50


[tool.pylint.dunder]
good-dunder-names = [
  "__narwhals_namespace__",
  "__narwhals_series__",
  "__narwhals_dataframe__",
  "__narwhals_lazyframe__",
  "__native_namespace__",
  "__array__",
]

[tool.pylint.format]
indent-after-paren = 4
indent-string = "    "
max-line-length = 120
max-module-lines = 400
